### PR TITLE
Show upsell popup when editing pro fields

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

Added upsell popup and show it when editing the lock field if a license is expired or not available.

### Will affect visual aspect of the product

YES

### Screenshots

https://tinyurl.com/2bmmgwuf

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/ppom-pro/issues/381

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@girishpanchal30 I've tested with no license entered at all.
In this case, I got these warnings
Screenshot on 2024-09-14 at 10-15-15

Also, after clicking on the Renew License button, I am redirected to this, not sure if correct
Screenshot on 2024-09-14 at 10-15-57

**Comment by girishpanchal30** [comment]
@rodica-andronache I fixed the warnings and the `Renew License` URL is working for me, please check with the latest build zip.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I tested it now, and it works as expected!
image

One question: should we add an overlay to make the rest of the screen not accessible anymore?
Right now, while I have the alert on the screen, I can still perform other actions, like enabling/disabling fields:
image

I can even switch to the style tab and write some code.

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Added background overlay, please check with the latest commit.

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Pull request merged**
