### PR TITLE
feat: add price multiplier for Measure Input

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

Add Price Multiplier feature for Measure Input.

### Will affect visual aspect of the product

NO

### Screenshots 

image

image

image

### Test instructions

- Create a Mesure input
- Set a price multiplier
- Purchase a product and check the value of the final price

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/ppom-pro/issues/430

### CODE REVIEW

**Comment by selul** [comment]
@Soare-Robert-Daniel I can't save the group with the measure input having a value on multiplier. 
Getting this error https://vertis.d.pr/i/7TUIBr

**Comment by Soare-Robert-Daniel** [comment]
@selul did you get the error with numbers like `0.055`?

**Comment by selul** [comment]
I used 0.01

**Comment by Soare-Robert-Daniel** [comment]
@selul I changed the field to `text` instead of `number`. I'm not sure what it does not like with those types of numbers.

**Comment by selul** [comment]
working great, thanks.

**Pull request merged**
