### PR TITLE
feat: add new condition options and improve UX & UI

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

Added new condition options for Free and Pro users. Improved the UI and UX.

Checklist:
- [x] Condition Target Select Input
  - [x] Support for dynamic filtering based on operator compatibility with the field type
  - [x] Complete compatibility list with all field types
- [x] Condition Operator Select Input
  - [x] Added new options
  - [x] Locking for PRO options
- [x] Comparision Value Input Fields
  - [x] Change the field based on the operator type.
    - [x] Simple text field for text-based and numeric-based comparison
    - [x] Double numeric fields for `between` operator
    - [x] Hide the field for operators that do not use a second comparison value (`any`, `empty`)
- [x] Field Rendering
  - [x] Render the dataset value user for an operator that uses a second comparison value (`contains`, `not-contains`, `regex`, etc )
  - [x] Render the dataset value for `between` operator
  - [x] Locking for PRO features

> [!IMPORTANT]
> The majority of the fields are not tracked by the conditions scripts. For them to work, we need to create more watchers tailored for each field.

> [!NOTE]
> The code is very cumbersome, so much refactoring was done to simplify and better showcase the functionality.

### Will affect visual aspect of the product

YES

### Screenshots 

image

Screenshot 2024-09-20 at 18 27 57

### Test instructions

> [!NOTE]
> Not all fields are supported to be part of the conditions.

- Make some simple fields like text, select, radio.
- Add another field with conditions based on previously simple fields created.

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/ppom-pro/issues/429

### CODE REVIEW

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel, here are my observations:

For text conditions:
- if you click on any of those three options (contains, does not contain, matches regex), a dropdown will appear, instead of a texarea - https://vertis.d.pr/v/kOycET
- there are some typos: does not contains -> does not contain; matchs regex -> matches RegEx
- can we grey out the Numeric and Select type field conditions  when we have a text input? (only if it doesn't imply complications)

For number conditions:

- if you have two meta fields, like text and number, and you select the Number meta field, then click on one condition type (is odd), the number field will switch to the other meta field
- for the "between" type, I think we should call it "is between"; also, there are no ranges, you only have a dropdown
- for "is multiple of number", we should either enlarge that space or write just "is multiple of"

The behavior is visible here - https://vertis.d.pr/v/A4wg2u

For Select conditions:
- instead of "not" we should say "is not"
- the greater than and less than should be moved to the numeric conditions
image

Also, the phrase above the conditions should also contain an "if":
image

**Comment by Soare-Robert-Daniel** [comment]
> * [ ]  if you click on any of those three options (contains, does not contain, matches regex), a dropdown will appear, instead of a texarea - https://vertis.d.pr/v/kOycET
> * [ ]  also, there are no ranges, you only have a dropdown

Could not replicate.

> * [ ]  can we grey out the Numeric and Select type field conditions  when we have a text input? (only if it doesn't imply complications)
> * [ ]  if you have two meta fields, like text and number, and you select the Number meta field, then click on one condition type (is odd), the number field will switch to the other meta field

I added auto-disable based on the field type on the target selector. Until now, it was based on operator value, but it is not a good UX. This should also fix the second problem.

Screenshot 2024-09-23 at 21 09 00



> * [ ]  the greater than and less than should be moved to the numeric conditions

I moved to their categories, but for backward compatibility reasons, they will be only available to basic select type input.


> * [ ]  Also, the phrase above the conditions should also contain an "if":

Could not replicate. It should be like this:

image

**Review by HardeepAsrani — APPROVED** [review]

**Comment by AndreeaCristinaRadacina** [comment]
@Soare-Robert-Daniel, now, the Greater than and Less than appear under numerical type, but they cannot be selected:
image

Also, when text is selected, the numerical conditions are still available:
image

**Comment by Soare-Robert-Daniel** [comment]
The new changes:
- Upsell for operators marked as PRO
- When pressing on `Add Field`, the conditions tabs will be hidden since the way the modal is created conflicts with some initializations. 
- Rewordered the operator options.
- Improved the `greater than` and `less than` to work with both select types fields and text fields

**Comment by AndreeaCristinaRadacina** [comment]
For number, no condition type is available:
image

**Comment by Soare-Robert-Daniel** [comment]
New changes:
- added Number to the list of the observed fields for conditions
- Text and Number input checking is done now on typing instead of change (no longer need to click outside to the see the results )
- wider operator selector (and shorter value input since it needs to make to space to fit all)

### Operator selection for text field type

Screenshot 2024-09-25 at 17 39 07

### Operator selection for number field type

Screenshot 2024-09-25 at 17 41 41


### Operator selection for select field type
Screenshot 2024-09-25 at 17 40 23

**Comment by Soare-Robert-Daniel** [comment]
Added Email and Date as supported fields.

@selul @AndreeaCristinaRadacina Do you think that fields that are not supported should not be a part of the selector or should we show them as disabled (in the idea that it might be available in the future if they are asking for it)

Screenshot 2024-09-25 at 18 13 53

**Comment by selul** [comment]
fields that dont supoort conditions should be removed from dropdown for now.

**Comment by Soare-Robert-Daniel** [comment]
Some important things to keep in mind.

In the released version, the conditions work correctly only for the inputs `Select`, `Radio`, and `Switcher` on all operators. `Checkbox` works only with the `is` operator.

**Thus, any new field and operator you see in this PR that is not mentioned above are new and not regressions.**

Not all fields are supported, and from the supported fields, not all operators are compatible (technical or UX reasons).

New changes:
- `is` and `is not` are now available for supported text-based inputs and numeric inputs
- `Checkbox` supports only the operator `is` and `is not.`
- The fields table footer will only appear if you have more than 8 fields 
- Various layout fixing

**Pull request merged**
