### PR TITLE
Fixed texter textbox placement issue

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary
Fixed textbox placement issue 

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/ppom-pro/issues/394

### CODE REVIEW

**Comment by selul** [comment]
@girishpanchal30 this is not fixing the issue, we should keep the same width, not make this container larger. We should position the texters inside the image instead.

**Comment by girishpanchal30** [comment]
@selul I resolved the issue by using another way with this pro plugin [PR](https://github.com/Codeinwp/ppom-pro/pull/474)

**Comment by selul** [comment]
@girishpanchal30 I've added a comment there. This can be closed?

**Comment by girishpanchal30** [comment]
@selul Yes

**Pull request closed without merging**
