### PR TITLE
Added condition remove support

### LINKED ISSUE #232: Enhance Conditions Tab
At the moment, if you go to the conditions tab while working on a meta field and insert more conditions, you are not able to delete the last one. To do this, you need to delete and recreate the one above it:
image

I believe we can make things easier and use two buttons for the last field as we have in Add Options:
image

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

Enhanced the add/remove condition functionality in the conditions tab.

## Check before Pull Request is ready:

* [ ] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes #232

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@girishpanchal30 when I try to add multiple conditions, only the first one gets saved. I'm not sure if I'm doing something wrong https://vertis.d.pr/v/OL0XZE

``
https://stately-lobster-6b9bbb.vertisite.cloud/wp-admin/
user: rodica
pass: rodica
``

**Comment by girishpanchal30** [comment]
@rodica-andronache I've reviewed mentioned issue and fixed it with latest commit.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, the logic works well now, thank you!

Here are some other findings:
- the rules are not correctly named (Rule 2, Rule 2, Rule 2)
- we should add some top margin for the rule name

image

- the tooltip that appears next to Conditions contains the same text as the tooltip that appears next to Enable Conditions. We should use something different like: Use the dropdowns to set show/hide the field based on specific rules.
- remove the extra space that appears next to "only if", as there is no need for more
- make the All/Any dropdown smaller, because we don't have longer conditions

image

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've fixed the recommended changes with the latest commit.

For the tooltip text I've changed it in the PRO plugin as well, please check with this [PR](https://github.com/Codeinwp/ppom-pro/pull/463
) as well.

Thanks

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, great! everything works and looks as expected!

**Pull request merged**
