### PR TITLE
Dev/e2e

### PR DESCRIPTION
**Pull request by Soare-Robert-Daniel**
### Summary

Add E2E test infrastructure. 

### Will affect visual aspect of the product

NO

## Check before Pull Request is ready:

* [x] I have [written a test](CONTRIBUTING.md#writing-an-acceptance-test) and included it in this PR
* [x] I have [run all tests](CONTRIBUTING.md#run-tests) and they pass
* [x] The code passes when [running the PHP CodeSniffer](CONTRIBUTING.md#run-php-codesniffer)
* [x] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
* [x] [Security and Sanitization](CONTRIBUTING.md#security-and-sanitization) requirements have been followed
* [x] I have assigned a reviewer or two to review this PR (if you're not sure who to assign, we can do this step for you)

Closes https://github.com/Codeinwp/woocommerce-product-addon/issues/411

### CODE REVIEW

**Review by abaicus — COMMENTED** [review]
@Soare-Robert-Daniel Things look good from the e2e tests perspective.

Any reason we're removing the caching steps?

**Comment by Soare-Robert-Daniel** [comment]
@abaicus, I took this advise https://github.com/Codeinwp/themeisle-sdk/pull/240#discussion_r1742483715

**Comment by abaicus** [comment]
We're removing the yarn cache as well. I don't think that we have that many or heavy dependencies in this particular repo, but I still think caching them would be useful as a general practice.

We can maybe look into updating the action to a more recent version: https://github.com/actions/cache?tab=readme-ov-file#example-cache-workflow

Up to you if you consider the dependencies might be worth caching. Otherwise, the PR looks good.

**Comment by Soare-Robert-Daniel** [comment]
@abaicus, I Did a little research and found out that setup-node has a built-in cache on top of `action/cache.`

This should simplify the approach https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

image

**Comment by abaicus** [comment]
@Soare-Robert-Daniel Great! That's pretty neat 👍🏻

**Pull request merged**
