### PR TITLE
Dashboard changelog

### PR DESCRIPTION
**Pull request by mskapusuz**
### Summary

Changelog screen added (show PPOM Free and PPOM Pro(if activated) changelogs)
Screen Shot 2022-11-21 at 12 38 14

### Will affect visual aspect of the product

YES

### Test instructions

- Visit WP Admin->Left Menu->WooCommerce->PPOM Fields
- Click changelog in header nav
- Make sure the PRO changelog works well if PPOM Pro is installed. (If PPOM Pro is not installed, the Free/Pro dropdown is not shown.)
- Make sure no regression roughly in dashboards.

Closes https://github.com/Codeinwp/woocommerce-product-addon/issues/66.

### CODE REVIEW

**Comment by irinelenache** [comment]
@mskapusuz Tested and the changelog seems to work fine, except one thing:

- [ ] The html added in the changelog is not rendered https://vertis.d.pr/i/sLHIVG

**Comment by irinelenache** [comment]
@mskapusuz Thank you, now the links look as they should 🚀 

Found out there is a notice visible on the changelog screen https://vertis.d.pr/i/31UnNI

**Comment by mskapusuz** [comment]
> @mskapusuz Thank you, now the links look as they should 🚀
> 
> Found out there is a notice visible on the changelog screen https://vertis.d.pr/i/31UnNI

@irinelenache Thanks for your finding. I've just fixed it. 👍

**Comment by irinelenache** [comment]
@mskapusuz Everything's fine now, thanks 🚀

**Pull request merged**
