### PR TITLE
Added image alt tag support

### PR DESCRIPTION
**Pull request by girishpanchal30**
Closes Codeinwp/ppom-pro/issues/140

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the alt text isn't applied to all image inputs, there are some where it isn't working:

https://testppom.vertisite.cloud/product/image-dropdown-input/
https://testppom.vertisite.cloud/product/conditional-images-input/

Here are the credentials:
```
Username: demo-ppom-lite
Password: 9qh0qRtX
```

**Comment by girishpanchal30** [comment]
Hey @irinelenache,

I've added img alt support for other image fields in this PR https://github.com/Codeinwp/ppom-pro/pull/145.

@mskapusuz Would you kindly assist me with this? The action of creating a ZIP file and uploading it to Github S3 failed, and I'm unable to identify what went wrong.

Thanks

**Comment by mskapusuz** [comment]
> Hey @irinelenache,
> 
> I've added img alt support for other image fields in this PR [Codeinwp/ppom-pro#145](https://github.com/Codeinwp/ppom-pro/pull/145).
> 
> @mskapusuz Would you kindly assist me with this? The action of creating a ZIP file and uploading it to Github S3 failed, and I'm unable to identify what went wrong.
> 
> Thanks

hey @girishpanchal30 sometimes that happens. Can you please try again to run GH checks, that may help. Please let me know it doesn't help.

**Comment by mskapusuz** [comment]
> Hey @irinelenache,
> 
> I've added img alt support for other image fields in this PR [Codeinwp/ppom-pro#145](https://github.com/Codeinwp/ppom-pro/pull/145).
> 
> @mskapusuz Would you kindly assist me with this? The action of creating a ZIP file and uploading it to Github S3 failed, and I'm unable to identify what went wrong.
> 
> Thanks

hey @girishpanchal30 again. I also count with the same issue and investigated it, that was causing by wrong node version in GH workflow. The build workflow issue been fixed just now on development branch, fyi.

**Comment by irinelenache** [comment]
@girishpanchal30 Everything's fine now, thank you 🚀

**Pull request merged**
